### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by mkempster** [AdoptOpenJDK/openjdk-docker-build-tools#11]
Have been using these images for some time now - they're great but showing their age. Last published a year ago or thereabouts. The underlying ubuntu is 18.something and refreshing tooling like git based on ubuntu packages is proving troublesome to get them current enough.

Latest versions of the base image adoptopenjdk/openjdk11:latest are on ubuntu 20.04.

Are there plans to rebuild these utility images on current base images?

**Comment by dinogun** [comment]
I would suggest that you can use the official [maven](https://hub.docker.com/_/maven) images instead. The official images are already using adoptopenjdk images as base images and are actively maintained. Is there any particular reason why you want to continue to use these images ?

**Comment by mkempster** [comment]
No reason aside from inertia and not spotting that the world had changed under my feet. Thanks for the pointer to the updated official projects! I'll try switching the build pipeline over to them now.
