### ISSUE TITLE
Add maven toolchain generation

### ISSUE THREAD

**Issue by jgsuess** [AdoptOpenJDK/openjdk-docker-build-tools#15]
For builds that want to  configure via [maven toolchain](https://maven.apache.org/plugins/maven-toolchains-plugin/toolchains/jdk.html), it would be nice to have a default configuration available. Could you include that with the image, please?

**Comment by karianna** [comment]
We've moved to the Eclipse Adoptium Project. See github.com/adoptium and adoptium.net
