### ISSUE TITLE
add support for alpine?

### ISSUE THREAD

**Issue by MartinForReal** [AdoptOpenJDK/openjdk-docker-build-tools#9]
The images based on Alpine is small in size. And adoptopenjdk have support for alpine. Shall we add support for alpine too?

**Comment by karianna** [comment]
@dinogun Is this the correct repo for this Q?

**Comment by karianna** [comment]
@dinogun - Can this be closed?

**Comment by dinogun** [comment]
I think this can be a good question for the official maven [repo](https://github.com/carlossg/docker-maven).
